### semester list
GET http://localhost:8886/bill/semester/list
Accept: application/json;charset=UTF-8
Cache-Control: no-cache
USER_ID:-1
{}

### semester create
POST http://localhost:8886/bill/semester/create?name=2020新学期
Accept: application/json;charset=UTF-8
Cache-Control: no-cache
USER_ID:-1

### semester setAsDefault
POST http://localhost:8886/bill/semester/setAsDefault?id=14
Accept: application/json;charset=UTF-8
Cache-Control: no-cache
USER_ID:-1

### subject list
GET http://localhost:8886/bill/subject/list
Accept: application/json;charset=UTF-8
Cache-Control: no-cache
USER_ID:-1
{}

### subject create
POST http://localhost:8886/bill/subject/create?name=美术
Accept: application/json;charset=UTF-8
Cache-Control: no-cache
USER_ID:-1

###